services:
  database:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cleanthis
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db-data:/var/lib/mysql

  www:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8001:80"
    volumes:
      - ./www:/var/www/html/
    environment:
      DATABASE_URL: "pdo-mysql://host.docker.internal:3306/cleanthis?charset=utf8mb4" 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root 

volumes:
  db-data:

networks:
  default: